[2024-06-06T16:13:27.952+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T16:13:27.973+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_3 manual__2024-06-06T10:37:22.131699+00:00 [queued]>
[2024-06-06T16:13:27.980+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_3 manual__2024-06-06T10:37:22.131699+00:00 [queued]>
[2024-06-06T16:13:27.980+0530] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-06-06T16:13:27.998+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collect_data_3> on 2024-06-06 10:37:22.131699+00:00
[2024-06-06T16:13:28.002+0530] {standard_task_runner.py:63} INFO - Started process 46109 to run task
[2024-06-06T16:13:28.006+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_data_pipeline_dag', 'collect_data_3', 'manual__2024-06-06T10:37:22.131699+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpntakxf4z']
[2024-06-06T16:13:28.008+0530] {standard_task_runner.py:91} INFO - Job 67: Subtask collect_data_3
[2024-06-06T16:13:28.051+0530] {task_command.py:426} INFO - Running <TaskInstance: my_data_pipeline_dag.collect_data_3 manual__2024-06-06T10:37:22.131699+00:00 [running]> on host DESKTOP-J05K55U.
[2024-06-06T16:13:28.126+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_data_3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T10:37:22.131699+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T10:37:22.131699+00:00'
[2024-06-06T16:13:28.127+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T16:13:28.128+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-06T16:13:28.129+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python "/home/wsl/airflow/dags/Collect Data/test.py"']
[2024-06-06T16:13:28.137+0530] {subprocess.py:86} INFO - Output:
[2024-06-06T16:13:30.844+0530] {subprocess.py:93} INFO - 24/06/06 16:13:30 WARN Utils: Your hostname, DESKTOP-J05K55U resolves to a loopback address: 127.0.1.1; using 172.31.56.255 instead (on interface eth0)
[2024-06-06T16:13:30.847+0530] {subprocess.py:93} INFO - 24/06/06 16:13:30 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-06-06T16:13:32.331+0530] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-06-06T16:13:32.332+0530] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-06-06T16:13:32.610+0530] {subprocess.py:93} INFO - 24/06/06 16:13:32 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-06-06T16:13:33.675+0530] {subprocess.py:93} INFO - 24/06/06 16:13:33 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-06-06T16:13:40.588+0530] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 1) / 1]                                                                                <pyspark.sql.session.SparkSession object at 0x7fed13b65b10>
[2024-06-06T16:13:40.588+0530] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-06-06T16:13:40.589+0530] {subprocess.py:93} INFO -   File "/home/wsl/airflow/dags/Collect Data/test.py", line 61, in <module>
[2024-06-06T16:13:40.589+0530] {subprocess.py:93} INFO -     df_asia = spark.read.format("json").option('multiline', 'true').option("inferschema", 'true').load("asia.json")
[2024-06-06T16:13:40.589+0530] {subprocess.py:93} INFO -   File "/home/wsl/airflow_venv/lib/python3.10/site-packages/pyspark/sql/readwriter.py", line 307, in load
[2024-06-06T16:13:40.590+0530] {subprocess.py:93} INFO -     return self._df(self._jreader.load(path))
[2024-06-06T16:13:40.590+0530] {subprocess.py:93} INFO -   File "/home/wsl/airflow_venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2024-06-06T16:13:40.590+0530] {subprocess.py:93} INFO -     return_value = get_return_value(
[2024-06-06T16:13:40.590+0530] {subprocess.py:93} INFO -   File "/home/wsl/airflow_venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
[2024-06-06T16:13:40.590+0530] {subprocess.py:93} INFO -     raise converted from None
[2024-06-06T16:13:40.600+0530] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/airflowtmp8i7mfo9g/asia.json.
[2024-06-06T16:13:41.201+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-06T16:13:41.202+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T16:13:41.217+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-06T16:13:41.223+0530] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=my_data_pipeline_dag, task_id=collect_data_3, execution_date=20240606T103722, start_date=20240606T104327, end_date=20240606T104341
[2024-06-06T16:13:41.242+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 67 for task collect_data_3 (Bash command failed. The command returned a non-zero exit code 1.; 46109)
[2024-06-06T16:13:41.262+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T16:13:41.271+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T16:13:41.272+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
