[2024-06-14T17:32:09.648+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T17:32:09.701+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-06-14T11:44:23.474146+00:00 [queued]>
[2024-06-14T17:32:09.723+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-06-14T11:44:23.474146+00:00 [queued]>
[2024-06-14T17:32:09.723+0530] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-06-14T17:32:10.184+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collect_data_1> on 2024-06-14 11:44:23.474146+00:00
[2024-06-14T17:32:10.189+0530] {standard_task_runner.py:63} INFO - Started process 15155 to run task
[2024-06-14T17:32:10.194+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_data_pipeline_dag', 'collect_data_1', 'manual__2024-06-14T11:44:23.474146+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpngp_px6n']
[2024-06-14T17:32:10.197+0530] {standard_task_runner.py:91} INFO - Job 29: Subtask collect_data_1
[2024-06-14T17:32:15.651+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task collect_data_1 ((sqlite3.OperationalError) database is locked
[SQL: SELECT task_instance.try_number, task_instance.task_display_name, task_instance.task_id, task_instance.dag_id, task_instance.run_id, task_instance.map_index, task_instance.start_date, task_instance.end_date, task_instance.duration, task_instance.state, task_instance.max_tries, task_instance.hostname, task_instance.unixname, task_instance.job_id, task_instance.pool, task_instance.pool_slots, task_instance.queue, task_instance.priority_weight, task_instance.operator, task_instance.custom_operator_name, task_instance.queued_dttm, task_instance.queued_by_job_id, task_instance.pid, task_instance.executor_config, task_instance.updated_at, task_instance.rendered_map_index, task_instance.external_executor_id, task_instance.trigger_id, task_instance.trigger_timeout, task_instance.next_method, task_instance.next_kwargs, dag_run_1.state AS state_1, dag_run_1.id, dag_run_1.dag_id AS dag_id_1, dag_run_1.queued_at, dag_run_1.execution_date, dag_run_1.start_date AS start_date_1, dag_run_1.end_date AS end_date_1, dag_run_1.run_id AS run_id_1, dag_run_1.creating_job_id, dag_run_1.external_trigger, dag_run_1.run_type, dag_run_1.conf, dag_run_1.data_interval_start, dag_run_1.data_interval_end, dag_run_1.last_scheduling_decision, dag_run_1.dag_hash, dag_run_1.log_template_id, dag_run_1.updated_at AS updated_at_1, dag_run_1.clear_number 
FROM task_instance JOIN dag_run AS dag_run_1 ON dag_run_1.dag_id = task_instance.dag_id AND dag_run_1.run_id = task_instance.run_id 
WHERE task_instance.dag_id = ? AND task_instance.run_id = ? AND task_instance.task_id = ? AND task_instance.map_index = ?]
[parameters: ('my_data_pipeline_dag', 'manual__2024-06-14T09:49:52.940074+00:00', 'collect_data_1', -1)]
(Background on this error at: https://sqlalche.me/e/14/e3q8); 15155)
[2024-06-14T17:32:26.769+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T17:32:26.794+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T17:32:26.795+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
