[2024-05-28T20:19:39.678+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T20:19:39.705+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T08:59:40.829093+00:00 [queued]>
[2024-05-28T20:19:39.712+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T08:59:40.829093+00:00 [queued]>
[2024-05-28T20:19:39.712+0530] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-05-28T20:19:39.733+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collect_data_1> on 2024-05-28 08:59:40.829093+00:00
[2024-05-28T20:19:39.736+0530] {standard_task_runner.py:63} INFO - Started process 228099 to run task
[2024-05-28T20:19:39.740+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_data_pipeline_dag', 'collect_data_1', 'manual__2024-05-28T08:59:40.829093+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp0iq71tdn']
[2024-05-28T20:19:39.741+0530] {standard_task_runner.py:91} INFO - Job 34: Subtask collect_data_1
[2024-05-28T20:19:39.795+0530] {task_command.py:426} INFO - Running <TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T08:59:40.829093+00:00 [running]> on host DESKTOP-J05K55U.
[2024-05-28T20:19:39.870+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_data_1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T08:59:40.829093+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T08:59:40.829093+00:00'
[2024-05-28T20:19:39.873+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T20:19:39.874+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-28T20:19:39.875+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'C:/Users/user/Desktop/Python/Airflow/covid_19_europe.py']
[2024-05-28T20:19:39.884+0530] {subprocess.py:86} INFO - Output:
[2024-05-28T20:19:39.889+0530] {subprocess.py:93} INFO - /usr/bin/bash: line 1: C:/Users/user/Desktop/Python/Airflow/covid_19_europe.py: No such file or directory
[2024-05-28T20:19:39.890+0530] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-28T20:19:39.890+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T20:19:39.898+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-28T20:19:39.904+0530] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=my_data_pipeline_dag, task_id=collect_data_1, execution_date=20240528T085940, start_date=20240528T144939, end_date=20240528T144939
[2024-05-28T20:19:39.942+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task collect_data_1 (Bash command failed. The command returned a non-zero exit code 127.; 228099)
[2024-05-28T20:19:39.953+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T20:19:39.974+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T20:19:39.988+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
