[2024-05-28T20:19:44.895+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T20:19:44.919+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T14:21:37.642659+00:00 [queued]>
[2024-05-28T20:19:44.926+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T14:21:37.642659+00:00 [queued]>
[2024-05-28T20:19:44.926+0530] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-28T20:19:44.948+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collect_data_1> on 2024-05-28 14:21:37.642659+00:00
[2024-05-28T20:19:44.951+0530] {standard_task_runner.py:63} INFO - Started process 228104 to run task
[2024-05-28T20:19:44.955+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_data_pipeline_dag', 'collect_data_1', 'manual__2024-05-28T14:21:37.642659+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpbbue9jz7']
[2024-05-28T20:19:44.956+0530] {standard_task_runner.py:91} INFO - Job 35: Subtask collect_data_1
[2024-05-28T20:19:45.001+0530] {task_command.py:426} INFO - Running <TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T14:21:37.642659+00:00 [running]> on host DESKTOP-J05K55U.
[2024-05-28T20:19:45.065+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_data_1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T14:21:37.642659+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T14:21:37.642659+00:00'
[2024-05-28T20:19:45.068+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T20:19:45.068+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-28T20:19:45.069+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'C:/Users/user/Desktop/Python/Airflow/covid_19_europe.py']
[2024-05-28T20:19:45.075+0530] {subprocess.py:86} INFO - Output:
[2024-05-28T20:19:45.076+0530] {subprocess.py:93} INFO - /usr/bin/bash: line 1: C:/Users/user/Desktop/Python/Airflow/covid_19_europe.py: No such file or directory
[2024-05-28T20:19:45.076+0530] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-28T20:19:45.077+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T20:19:45.085+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-28T20:19:45.088+0530] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=my_data_pipeline_dag, task_id=collect_data_1, execution_date=20240528T142137, start_date=20240528T144944, end_date=20240528T144945
[2024-05-28T20:19:45.104+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task collect_data_1 (Bash command failed. The command returned a non-zero exit code 127.; 228104)
[2024-05-28T20:19:45.128+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T20:19:45.148+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T20:19:45.159+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
